nodeLinker: node-modules

npmRegistries:
  "https://npm.pkg.github.com":
    npmAlwaysAuth: true
    npmAuthToken: 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

npmScopes:
  rh-ogorod:
    npmRegistryServer: "https://npm.pkg.github.com"
    # npmAuthToken: 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
    # npmAlwaysAuth: true

packageExtensions:
  "eslint-config-next@*":
    dependencies:
      next: "*"
      react: "*"
      react-dom: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
